name = "OW3DHelper"
uuid = "f60267ad-b39f-48fa-bea0-d281e8f5a0c0"
authors = ["Kosuke Sando <kosukesando@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"

[compat]
LoopVectorization = "0.12.171"
ProgressLogging = "0.1.4"
TerminalLoggers = "0.1.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
