name = "OW3DHelper"
uuid = "f60267ad-b39f-48fa-bea0-d281e8f5a0c0"
authors = ["Kosuke Sando <kosukesando@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Printf = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
